version: '3.8'

services:
  ont-manager:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ont-manager
    environment:
      - TZ=America/Sao_Paulo
    restart: "no"
    ports:
      - "2222:22" 
    networks:
      - ont-network
      - lideri_databases

networks:
  ont-network:
    driver: bridge
  lideri_databases:
    external: true
    name: lideri_databases